---
- hosts: dev
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Install python
      apt:
        name: python3
        state: present
    - name: Install pip
      apt:
        name: pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: webapp
        image: "manju1921/webapp:{{DOCTAG}}"
        state: started
        restart_policy: always
        published_ports:
          - 0.0.0.0:80:80
